/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author fabinhosano
 */
public final class Simular extends javax.swing.JPanel {

    JFileChooser fileChooser;

    /**
     * Creates new form Simular
     */
    public Simular() {
        initComponents();

        carregarPanelSimular();

        fileChooser = new JFileChooser(
                new File("/home/fabinhosano/Dropbox/Iniciação Científica/Modelos"));
    }

    public void carregarPanelSimular() {
        //Desabilitando o campo de texto de saída
        textSaida.setEditable(false);

        //Desabilitando o botão simular para preenchimento correto dos campos
        buttonSimular.setEnabled(false);

        //Criando mecanismos de interação do Panel Treinar
        textTamanho.getDocument().addDocumentListener(criaMecanismosText());
        textQuant.getDocument().addDocumentListener(criaMecanismosText());
        textSaida.getDocument().addDocumentListener(criaMecanismosText());

    }

    private void verificaCamposPreenchidos() {
        if (textQuant.getText().equals("") || textSaida.getText().equals("")
                || textTamanho.getText().equals("")) {
            buttonSimular.setEnabled(false);
        } else {
            buttonSimular.setEnabled(true);
        }
    }

    private DocumentListener criaMecanismosText() {
        DocumentListener dl = new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
            }

            public void removeUpdate(DocumentEvent e) {
                verificaCamposPreenchidos();
            }

            public void insertUpdate(DocumentEvent e) {
                verificaCamposPreenchidos();
            }
        };
        
        return dl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSimular = new javax.swing.JLabel();
        labelTamanho = new javax.swing.JLabel();
        textTamanho = new javax.swing.JTextField();
        labelQuant = new javax.swing.JLabel();
        textQuant = new javax.swing.JTextField();
        labelSaida = new javax.swing.JLabel();
        textSaida = new javax.swing.JTextField();
        buttonSaida = new javax.swing.JButton();
        buttonSimular = new javax.swing.JButton();

        labelSimular.setText("SIMULAR");

        labelTamanho.setText("Tamanho");

        labelQuant.setText("Quantidade");

        labelSaida.setText("Saída");

        buttonSaida.setText("Selecionar");
        buttonSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaidaActionPerformed(evt);
            }
        });

        buttonSimular.setText("SIMULAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSimular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelQuant)
                                .addComponent(labelSaida)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textQuant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(labelTamanho, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTamanho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(textSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonSaida)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSimular)
                .addGap(18, 18, 18)
                .addComponent(labelTamanho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelQuant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSimular)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaidaActionPerformed
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            textSaida.setText(fileChooser.getSelectedFile().getAbsolutePath());

        }
    }//GEN-LAST:event_buttonSaidaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSaida;
    private javax.swing.JButton buttonSimular;
    private javax.swing.JLabel labelQuant;
    private javax.swing.JLabel labelSaida;
    private javax.swing.JLabel labelSimular;
    private javax.swing.JLabel labelTamanho;
    private javax.swing.JTextField textQuant;
    private javax.swing.JTextField textSaida;
    private javax.swing.JTextField textTamanho;
    // End of variables declaration//GEN-END:variables
}
