/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author fabinhosano
 */
public final class Treinar extends javax.swing.JPanel {

    JFileChooser fileChooser;

    /**
     * Creates new form Treinar
     */
    public Treinar() {
        initComponents();

        carregarPanelSimular();

        fileChooser = new JFileChooser(
                new File("/home/fabinhosano/Dropbox/Iniciação Científica/Modelos"));
    }

    public void carregarPanelSimular() {
        //Desabilitando os campos de texto do panel Treinar
        textSaida.setEditable(false);
        textArqConf.setEditable(false);
        textAlfabeto.setEditable(false);

        //Desabilitando o botão simular para preenchimento correto dos campos
        buttonTreinar.setEnabled(false);

        //Criando mecanismos de interação do Panel Treinar
        textArqConf.getDocument().addDocumentListener(criaMecanismosText());
        textAlfabeto.getDocument().addDocumentListener(criaMecanismosText());
        textSaida.getDocument().addDocumentListener(criaMecanismosText());

    }

    private void verificaCamposPreenchidos() {
        if (textArqConf.getText().equals("") || textSaida.getText().equals("")
                || textAlfabeto.getText().equals("")) {
            buttonTreinar.setEnabled(false);
        } else {
            buttonTreinar.setEnabled(true);
        }
    }

    private DocumentListener criaMecanismosText() {
        DocumentListener dl = new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
            }

            public void removeUpdate(DocumentEvent e) {
                verificaCamposPreenchidos();
            }

            public void insertUpdate(DocumentEvent e) {
                verificaCamposPreenchidos();
            }
        };

        return dl;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTreinar = new javax.swing.JLabel();
        labelArqSeq = new javax.swing.JLabel();
        textArqConf = new javax.swing.JTextField();
        buttonArqConf = new javax.swing.JButton();
        labelSeq = new javax.swing.JLabel();
        textAlfabeto = new javax.swing.JTextField();
        buttonSeq = new javax.swing.JButton();
        labelSaida = new javax.swing.JLabel();
        textSaida = new javax.swing.JTextField();
        buttonSaida = new javax.swing.JButton();
        buttonTreinar = new javax.swing.JButton();

        labelTreinar.setText("TREINAR");

        labelArqSeq.setText("Arquivo de Sequência");

        buttonArqConf.setText("Selecionar");
        buttonArqConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonArqConfActionPerformed(evt);
            }
        });

        labelSeq.setText("Alfabeto (separado por vírgula)");

        buttonSeq.setText("Selecionar");
        buttonSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeqActionPerformed(evt);
            }
        });

        labelSaida.setText("Saída");

        buttonSaida.setText("Selecionar");
        buttonSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaidaActionPerformed(evt);
            }
        });

        buttonTreinar.setText("TREINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArqSeq)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonTreinar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(textArqConf, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonArqConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(labelSeq, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(textAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSeq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(labelSaida, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(textSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSaida)))
                    .addComponent(labelTreinar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTreinar)
                .addGap(18, 18, 18)
                .addComponent(labelArqSeq)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textArqConf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonArqConf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSeq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonTreinar)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonArqConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonArqConfActionPerformed
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            textArqConf.setText(fileChooser.getSelectedFile().getAbsolutePath());

        }
    }//GEN-LAST:event_buttonArqConfActionPerformed

    private void buttonSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeqActionPerformed
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            textAlfabeto.setText(fileChooser.getSelectedFile().getAbsolutePath());

        }
    }//GEN-LAST:event_buttonSeqActionPerformed

    private void buttonSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaidaActionPerformed
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            textSaida.setText(fileChooser.getSelectedFile().getAbsolutePath());

        }
    }//GEN-LAST:event_buttonSaidaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonArqConf;
    private javax.swing.JButton buttonSaida;
    private javax.swing.JButton buttonSeq;
    private javax.swing.JButton buttonTreinar;
    private javax.swing.JLabel labelArqSeq;
    private javax.swing.JLabel labelSaida;
    private javax.swing.JLabel labelSeq;
    private javax.swing.JLabel labelTreinar;
    private javax.swing.JTextField textAlfabeto;
    private javax.swing.JTextField textArqConf;
    private javax.swing.JTextField textSaida;
    // End of variables declaration//GEN-END:variables
}
